# Generated by Django 4.0.5 on 2022-12-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pa_nombre', models.CharField(max_length=20)),
                ('pa_apellido', models.CharField(max_length=30)),
                ('pa_rut', models.IntegerField()),
                ('pa_edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=2)),
                ('seguro', models.CharField(max_length=20)),
                ('fec_ingreso', models.DateField()),
            ],
        ),
    ]
