# Generated by Django 4.0.5 on 2022-12-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet_Galenos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='id_paciente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
