# Generated by Django 4.0.5 on 2022-12-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet_Galenos', '0004_medicos_delete_horasmedicas_alter_pacientes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientes',
            options={'ordering': ['pa_nombre', '-pa_apellido'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
