# Generated by Django 4.0.5 on 2022-12-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet_Galenos', '0006_alter_medicos_options_medicos_dia_salida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicos',
            name='dia_ingreso',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='dia_salida',
        ),
        migrations.RemoveField(
            model_name='medicos',
            name='dias_trabajo',
        ),
    ]
