# Generated by Django 4.0.5 on 2022-12-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet_Galenos', '0007_remove_medicos_dia_ingreso_remove_medicos_dia_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasmedicas',
            name='id_horamedica',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
