# Generated by Django 4.0.5 on 2022-12-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet_Galenos', '0014_alter_horasmedicas_fec_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasmedicas',
            name='medico',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horasmedicas',
            name='paciente',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
